# Generated by Django 2.1.1 on 2018-09-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortdrinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='price_per_liter',
        ),
    ]
